version: '3'
services:
   etl:
      build: .
      container_name: updayetl
      depends_on:
         - postgres
      links:
         - postgres
      environment: 
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_HOST: postgres
         POSTGRES_PORT: 5432
         POSTGRES_DB: upday
      volumes:
         - ./data:/home/data
         - ./etl.py:/usr/spark-2.4.1/etl.py
      # entrypoint:
      #    - "python /usr/spark-2.4.1/etl.py"
      # command: |
      #    "python /usr/spark-2.4.1/etl.py"
   postgres:
      build: postgres/docker
      image: postgres
      restart: always
      container_name: updaydb
      ports:
         - "5432:5432"
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: upday
   
